### PR TITLE
Add rounded cylinder.

### PR DESCRIPTION
**Pull request by michaelkuty**

### CODE REVIEW

**Comment by JustinSDK** [comment]
There's a better way to implement a rounded cylinder instead of using `hull`. I'll provide one in the future.

**Comment by michaelkuty** [comment]
Thanks

**Comment by JustinSDK** [comment]
It still gives some idea to rounded_xxx :)

**Comment by JustinSDK** [comment]
Check it 
https://openhome.cc/eGossip/OpenSCAD/lib-rounded_cylinder.html

**Comment by michaelkuty** [comment]
Nice, thanks for info, i will try it today

Dne 11. 5. 2017 9:27 napsal uživatel "Justin Lin" <notifications@github.com

**Pull request closed without merging**
